#!/bin/bash

set -eux

shopt -s nullglob

cd $(dirname "$0")
BASE=$(pwd)

CONFIGDIR=$BASE/cgi-bin
DATADIR=$BASE/data

mkdir -p $DATADIR

#ls -l $HOME/logs/*/http{,s}/access.log.$(date -I --date=yesterday)

for LOGFILE in $HOME/logs/*/http{,s}/access.log.0
do
	[[ "$LOGFILE" =~ logs/(.+)/(http|https) ]]
	SITE=${BASH_REMATCH[1]}
	PROTOCOL=${BASH_REMATCH[2]}
	case $PROTOCOL in
	https) CONFIG=${SITE} ; HTTPSLINKS='/' ;;
	    *) CONFIG=${SITE}-${PROTOCOL} ; HTTPSLINKS='' ;;
	esac
	CONFIG_PATH=$CONFIGDIR/awstats.$CONFIG.conf
	LOCAL_CONFIG_PATH=$BASE/awstats.$CONFIG.conf
	if [[ ${1:-} == 'all' ]]
	then
		LOGFILE="zcat -f $HOME/logs/$SITE/$PROTOCOL/access.log.2* |"
	fi
	cat > $CONFIG_PATH <<ENDCONFIG
DirData="$DATADIR"
Include "$BASE/awstats.common.conf"
LogFile="$LOGFILE"
SiteDomain="$SITE"
HostAliases="www.$SITE"
UseHTTPSLinkForUrl="$HTTPSLINKS"
ENDCONFIG
	if [[ -f $LOCAL_CONFIG_PATH ]]
	then
		cat $LOCAL_CONFIG_PATH >> $CONFIG_PATH
	fi

	$BASE/awstats/wwwroot/cgi-bin/awstats.pl -configdir=$CONFIGDIR -config=$CONFIG -update
done
