#!/bin/bash

set -eux

shopt -s nullglob

cd $(dirname "$0")
BASE=$(pwd)

CONFIGDIR=$BASE/cgi-bin
DATADIR=$BASE/data

LOGSDIR=$HOME/logs

mkdir -p $DATADIR

function write_config {
	cat > $CONFIG_PATH <<ENDCONFIG
DirData="$DATADIR"
Include "$BASE/awstats.common.conf"
LogFile="$1"
SiteDomain="$SITE"
HostAliases="www.$SITE"
UseHTTPSLinkForUrl="$HTTPSLINKS"
ENDCONFIG
	if [[ -f $LOCAL_CONFIG_PATH ]]
	then
		cat $LOCAL_CONFIG_PATH >> $CONFIG_PATH
	fi
}

for LOG in $(find $LOGSDIR/*/http{s,}/access.log -mtime -31)
do
	[[ "$LOG" =~ logs/(.+)/(http|https) ]]
	SITE=${BASH_REMATCH[1]}
	PROTOCOL=${BASH_REMATCH[2]}
	case $PROTOCOL in
	https) CONFIG=${SITE} ; HTTPSLINKS='/' ;;
	    *) CONFIG=${SITE}-${PROTOCOL} ; HTTPSLINKS='' ;;
	esac
	CONFIG_PATH=$CONFIGDIR/awstats.$CONFIG.conf
	LOCAL_CONFIG_PATH=$BASE/awstats.$CONFIG.conf
	if [ -f "$LOGSDIR/$SITE/$PROTOCOL/access.log.0" ]
	then
		LOGALLCMD="cd $LOGSDIR/$SITE/$PROTOCOL && zcat -f access.log{.2*,} |"
		LOGDAYCMD="cd $LOGSDIR/$SITE/$PROTOCOL && cat access.log{.0,} |"
	else
		LOGALLCMD="cd $LOGSDIR/$SITE/$PROTOCOL && cat access.log |"
		LOGDAYCMD="cd $LOGSDIR/$SITE/$PROTOCOL && cat access.log |"
	fi
	case ${1:-all} in
	all) write_config "$LOGALLCMD" ;;
	day) write_config "$LOGDAYCMD" ;;
	esac

	$BASE/awstats/wwwroot/cgi-bin/awstats.pl -configdir=$CONFIGDIR -config=$CONFIG -update

	# Rewrite config with all logs to better support rawlog searches
	write_config "$LOGALLCMD"
done
